<a href="https://colab.research.google.com/github/johnpaulzaralspu/ZARA-CSST_101-BSCS_3B/blob/main/CSST101_Exer3_CourseEnrollment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Create the Student Database**

In [ ]:
students <- data.frame(
  Student_ID = c("S001", "S002", "S003", "S004", "S005", "S006", "S007", "S008"),
  Programming_Grade = c(88, 72, 91, 78, 65, 85, 74, 82),
  Math_Grade = c(85, 70, 88, 80, 68, 90, 73, 79),
  Attendance = c(92, 80, 95, 88, 70, 91, 76, 85),
  Prerequisite = c("Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes")
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes

# **2. Explore the Data**

In [ ]:
summary(students)


# cat("Rows:", nrow(students))
# cat("\nColumns:", ncol(students))
# cat("\nMax:", max(students$Programming_Grade))
# cat("\nMax:", max(students$Math_Grade))
# cat("\nMax:", max(students$Attendance))
# cat("\nMax:", max(students$Prerequisite))

# cat("\nMin:",min(students$Programming_Grade))
# cat("\nMin:",min(students$Math_Grade))
# cat("\nMin:",min(students$Attendance))
# cat("\nMin:",min(students$Prerequisite))

#...

     Student_ID Programming_Grade   Math_Grade      Attendance
 Length   :8    Min.   :65.00     Min.   :68.00   Min.   :70.00
 N.unique :8    1st Qu.:73.50     1st Qu.:72.25   1st Qu.:79.00
 N.blank  :0    Median :80.00     Median :79.50   Median :86.50
 Min.nchar:4    Mean   :79.38     Mean   :79.12   Mean   :84.62
 Max.nchar:4    3rd Qu.:85.75     3rd Qu.:85.75   3rd Qu.:91.25
                Max.   :91.00     Max.   :90.00   Max.   :95.00
    Prerequisite
 Length   :8
 N.unique :2
 N.blank  :0
 Min.nchar:2
 Max.nchar:3

# **3. Enter a Student ID**

In [ ]:
student_id <- readline("Enter Student ID: ")
print(student_id)

Enter Student ID: S001
[1] "S001"

# **4. Search the Data Frame**

In [ ]:
student <- students[students$Student_ID == student_id,]

student

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes

# **5. Check if the Students Exist**

In [ ]:
if (nrow(student) > 0) {
  print("Found it! Student Exists")
} else {
   print("Student id not found")
}

[1] "Found it! Student Exists"

# **6. Extract Student Information**

In [ ]:
student_id <- student$Student_ID
programming <- student$Programming_Grade
math <- student$Math_Grade
attendance <- student$Attendance
prereq <- student$Prerequisite

cat("Student ID        : ", student_id)
cat("\nProgramming Grade : ", programming)
cat("\nMath Grade        : ", math)
cat("\nAttendance        : ", attendance)
cat("\nPrerequisite      : ", prereq)

Student ID        :  S001
Programming Grade :  88
Math Grade        :  85
Attendance        :  92
Prerequisite      :  Yes

# **7. Implement the Rules**

**Rule 1 -** *Eligible*: Programming Grade >= 80 AND Math Grade >= 75 AND Attendance >= 80% AND Prerequisite = Yes.

**Rule 2 -** *Conditional Eligible*:  Programming Grade >= 75 AND Math Grade >= 70 AND Attendance >= 75%, but Rule 1 is not satisfied.

**Rule 3 -** *Not Eligible*: If neither Rule 1 nor Rule 2 is satisfied, classify the student as Not Eligible.

In [ ]:
check_eligibility <- function(programming, math, attendance, prereq) {

  if (programming >= 80 &&
      math >= 75 &&
      attendance >= 80 &&
      prereq == "Yes") {
    return("Eligible")

  } else if (programming >= 75 &&
             math >= 70 &&
             attendance >= 75) {
    return("Conditional Eligible")

  } else {
    return("Not Eligible")

  }
}

eligibility <- check_eligibility(
  programming,
  math,
  attendance,
  prereq
)

cat("Eligibility Status:", eligibility)

Eligibility Status: Eligible

# **8. Apply the Function to All Students**

In [ ]:
students$Eligibility <- mapply(
  check_eligibility,
  students$Programming_Grade,
  students$Math_Grade,
  students$Attendance,
  students$Prerequisite
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligibility
1 Eligible
2 Not Eligible
3 Eligible
4 Conditional Eligible
5 Not Eligible
6 Eligible
7 Not Eligible
8 Eligible

# **9. Create Recommendation Rules**

  **1. Eligible =** Student may Enroll
  
  **2. Conditional Eligible =** Consult Academic Adviser

  **3. Not Eligible =** Complete requirements before enrollment

In [ ]:
get_recommendation <- function(eligibility) {

  if (eligibility == "Eligible") {
    return("Student may Enroll")

  } else if (eligibility == "Conditional Eligible") {
    return("Consult Academic Adviser")

  } else {
    return("Complete requirements before enrollment")
  }
}

students$Recommendation <- sapply(
  students$Eligibility,
  get_recommendation
)

students

  Student_ID Programming_Grade Math_Grade Attendance Prerequisite
1 S001       88                85         92         Yes
2 S002       72                70         80         No
3 S003       91                88         95         Yes
4 S004       78                80         88         Yes
5 S005       65                68         70         No
6 S006       85                90         91         Yes
7 S007       74                73         76         No
8 S008       82                79         85         Yes
  Eligibility          Recommendation
1 Eligible             Student may Enroll
2 Not Eligible         Complete requirements before enrollment
3 Eligible             Student may Enroll
4 Conditional Eligible Consult Academic Adviser
5 Not Eligible         Complete requirements before enrollment
6 Eligible             Student may Enroll
7 Not Eligible         Complete requirements before enrollment
8 Eligible             Student may Enroll

# **10. Expected Output**

In [ ]:

student_id <- readline(prompt = "Enter Student ID: ")

student <- students[students$Student_ID == student_id, ]

if (nrow(student) > 0) {

  cat("\n========================================\n")
  cat("       COURSE ENROLLMENT ADVISER\n")
  cat("========================================\n\n")

  cat("Student ID:", student$Student_ID, "\n\n")

  cat("Programming Grade:", student$Programming_Grade, "\n")
  cat("Math Grade:", student$Math_Grade, "\n")
  cat("Attendance:", student$Attendance, "%\n")
  cat("Prerequisite:", student$Prerequisite, "\n\n")

  cat("Enrollment Status:\n")
  cat(student$Eligibility, "\n\n")

  cat("Recommendation:\n")
  cat(student$Recommendation, "\n")

  cat("========================================\n")

} else {
  cat("\nStudent ID not found.\n")
}

Enter Student ID: S004

========================================
       COURSE ENROLLMENT ADVISER
========================================

Student ID: S004

Programming Grade: 78
Math Grade: 80
Attendance: 88 %
Prerequisite: Yes

Enrollment Status:
Conditional Eligible

Recommendation:
Consult Academic Adviser
========================================